# conda environment named tripod using the latest version of python
name: tripod
dependencies:
  - pip
  - pip:
    - ipykernel
    - lightning
    - matplotlib
    - scipy
    - torch
    - torchvision
  - python
