# conda environment named tripod using the latest version of python
name: tripod
dependencies:
  - ipython
  - pip
  - pip:
    - ipykernel
    - ipywidgets
    - lightning
    - matplotlib
    - pandas
    - pytorch-msssim
    - scipy
    - scikit-image
    - segmentation-models-pytorch
    - tensorboard
    - torch
    - torchinfo
    - torchvision
  - python=3.10
