# conda environment named tripod using the latest version of python
name: tripod
dependencies:
  - pip
  - pip:
    - ipykernel
    - ipywidgets
    - lightning
    - matplotlib
    - scipy
    - segmentation-models-pytorch
    - torch
    - torchinfo
    - torchvision
  - python=3.10
